<h1 style="text-align: center;">Working with data with Numpy and Pandas 📊</h1>

<font size="4"> **NumPy** (Numerical Python) is the fundamental library for numerical computing in Python, essential for data analysis, statistical computations, and scientific research. This notebook does not cover all the functions you can carry out with NumPy, but it does include most of the elements you need for your research activities. For more information, please visit [Numpy Learning Hub](https://numpy.org/learn/).</font>

<font size="4">**What is NumPy and Why Use It?**</font>

<font size="4">NumPy provides powerful tools for working with multidimensional arrays and performing vectorized operations, making data manipulation significantly faster than standard Python lists. For psychology researchers, NumPy enables efficient handling of experimental data, participant scores, reaction times, and other numerical measurements collected during studies.</font>

<font size="4">**Creating and Understanding Arrays**</font>

<font size="4">Core Concepts:</font>

- <font size="4">**Arrays**: The fundamental data structure in NumPy, similar to lists but optimized for numerical operations</font>

- <font size="4">**Dimensions**: Arrays can be 1D (like a single participant's responses), 2D (like a data matrix with participants × trials), or higher</font>

- <font size="4">**Data types**: NumPy arrays store elements of a single type (integers, floats, etc.) for efficiency</font>

<h1 style="text-align: center;">Creating Arrays</h1>

<font size="4">NumPy is an external package, so you need to import it before using its functions to analyze your data (typically with `import numpy as np`).</font>

<font size="4">In practice, you usually import it once at the start of a notebook or script, and then you can use it throughout the rest of your code.</font>

In [ ]:
import numpy as np

In [ ]:
# 1. Creating a 1D Array (Vector)
# Example: A single list of IQ scores for 6 different participants
iq_scores = np.array([105, 112, 98, 120, 115, 103])
print(f"The following six participants' IQ scores are shown in this example: {iq_scores}")

In [ ]:
# 2. Creating a 2D Array (Matrix)
# Example: Reaction times (ms) for 3 participants across 4 distinct trials
# The structure is (Rows, Columns) -> (3 Participants, 4 Trials)
reaction_times = np.array([
    [250, 245, 260, 255],  # Row 0: Participant 1's trials
    [310, 305, 298, 302],  # Row 1: Participant 2's trials
    [275, 280, 270, 278]   # Row 2: Participant 3's trials
])
print(f"The 2D array matrix is shown in this example: \n{reaction_times}")

In [ ]:
# 3. Generating Placeholders and Random Data
# Useful for initializing data structures before an experiment begins

# Create an empty container for 10 data points (initialized to 0)
empty_container = np.zeros(10)
print(f"This is an empty container of zeros: {empty_container}")

# Create a 3x4 matrix filled with 1s (3 rows, 4 columns)
ones_matrix = np.ones((3, 4))
print(f"This is a 3x4 matrix filled with 1s: \n {ones_matrix}")

# Create a 5x3 matrix of random data from a standard normal distribution
# (Mean = 0, Std Dev = 1), often used for simulations
simulated_data = np.random.randn(5, 3)
print(f"This is a 5x3 matrix of random data from a standard normal distribution: \n {simulated_data}")

In [ ]:
# ---------------------------------------------------------
# EXERCISE 1: Creating Arrays
# ---------------------------------------------------------

# 1. Create a 1D array containing the ages of 8 participants: 
#    Ages: [22, 25, 19, 30, 28, 21, 24, 26]
#    Hint: Use np.array([]) with a list of numbers inside.

# ... write your code here ..


# 2. Create a 2D array representing anxiety scores (scale 1-10) 
#    for 5 participants measured at 3 time points.
#    Use the following data:
#      - Participant 1: [7, 6, 5]
#      - Participant 2: [8, 8, 7]
#      - Participant 3: [4, 3, 3]
#      - Participant 4: [9, 8, 6]
#      - Participant 5: [5, 5, 4]
#    
#    Hint: This should be a list of lists -> [[...], [...], ...]

# ... write your code here ...


# 3. Create a 10x5 array of zeros to prepare for storing future data 
#    from 10 participants across 5 conditions.
#
#    Hint: Use the np.zeros() function. Remember that the shape 
#    arguments for multi-dimensional arrays must be in parentheses! 
#    Example: np.zeros((rows, columns))

# ... write your code here ...

<details>
  <summary>Click here to see the solution 💡</summary>
  <br>
  <b> Solution:</b>
  <pre>
      
<font size="2">**1. Create a 1D array containing the ages of 8 participants**</font>
participant_ages = np.array([22, 25, 19, 30, 28, 21, 24, 26])
print(f"Participant Ages (1D Array): {participant_ages}")

<font size="2">**2. Create a 2D array representing anxiety scores**</font>
anxiety_scores = np.array([
    [7, 6, 5],
    [8, 8, 7],
    [4, 3, 3],
    [9, 8, 6],
    [5, 5, 4]
])

print(f"Anxiety Scores (2D Array - 5 Participants x 3 Timepoints): \n {anxiety_scores}")

<font size="2">**3. Create a 10x5 array of zeros**</font>
future_data_container = np.zeros((10, 5))
print(f"Future Data Container (Zeros - 10 Participants x 5 Conditions): \n {future_data_container}")

  </pre> 
  <br>
  <b>Expected Output:</b>
  <pre>
      
Participant Ages (1D Array):
[22 25 19 30 28 21 24 26]


Anxiety Scores (2D Array - 5 Participants x 3 Timepoints):
[[7 6 5]
 [8 8 7]
 [4 3 3]
 [9 8 6]
 [5 5 4]]


Future Data Container (Zeros - 10 Participants x 5 Conditions):
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

  </pre>
  <p><i>Note the difference in output formatting between the 1D and 2D arrays.</i></p>
</details>

<h2 style="text-align: center;">Array Attributes and Inspection</h2>

<font size="4">Once you have created an array, you often need to check its structure to ensure your data was loaded correctly.</font>

In [ ]:
# Imagine this represents data from 2 participants across 3 experimental conditions
data = np.array([
    [1, 2, 3],  # Participant 1
    [4, 5, 6]   # Participant 2
])

# 1. Shape: Returns a tuple (Rows, Columns)
# Very useful for checking sample size (N) and number of variables
print(f"Shape: {data.shape}")  # Output: (2, 3) -> 2 participants, 3 conditions

# 2. Number of Dimensions (ndim)
# 1 = Vector, 2 = Matrix, 3+ = Tensor (e.g., MRI data)
print(f"Dimensions: {data.ndim}")  # Output: 2

# 3. Size: Total number of individual data points
print(f"Total Elements: {data.size}")  # Output: 6

# 4. Data Type (dtype): The type of data stored (int, float, etc.)
print(f"Data Type: {data.dtype}")  # Output: int64 (or int32)


In [ ]:
# ---------------------------------------------------------
# EXERCISE 2: Array Inspection
# ---------------------------------------------------------

# NOTE: This exercise relies on the 'anxiety_scores' array 
# you created in Exercise 1.

# 1. Print the shape, number of dimensions (ndim), and total size 
#    of the 'anxiety_scores' array.

# ... write your code here ...


# 2. Create a variable called 'n_participants' by extracting the 
#    number of rows from the .shape attribute (index 0).
#    Hint: array.shape returns a tuple like (rows, columns).

# ... write your code here ...


# 3. Create a variable called 'n_timepoints' by extracting the 
#    number of columns from the .shape attribute (index 1).

# ... write your code here ...


# 4. Print a sentence summing up the study design: 
#    "This dataset contains X participants measured at Y timepoints."
#    Hint: Use an f-string to insert your new variables.

# ... write your code here ...

<details>
  <summary>Click here to see the solution 💡</summary>
  <br>
  <b> Solution:</b>
  <pre>

anxiety_scores = np.array([
    [7, 6, 5],
    [8, 8, 7],
    [4, 3, 3],
    [9, 8, 6],
    [5, 5, 4]
])
      
<font size="2">**1. Inspecting Array Properties**</font>
print(f"Shape: {anxiety_scores.shape}")
print(f"Number of dimensions: {anxiety_scores.ndim}")
print(f"Total size (elements): {anxiety_scores.size}")
print("-" * 30)

<font size="2">**2. Extracting Participants (Rows)**</font>
n_participants = anxiety_scores.shape[0]

<font size="2">**3. Extracting Timepoints (Columns)**</font>
n_timepoints = anxiety_scores.shape[1]

<font size="2">**4. Summary Sentence**</font>
print(f"This dataset contains {n_participants} participants measured at {n_timepoints} timepoints.")
print("-" * 30)
  </pre> 
  <br>
  <b>Expected Output:</b>
  <pre>
Shape: (5, 3)
Number of dimensions: 2
Total size (elements): 15

------------------------------
This dataset contains 5 participants measured at 3 timepoints.
  </pre>
  <p><i>The <code>.shape</code> attribute is a tuple, so we access the number of rows (participants) at index 0 and columns (timepoints) at index 1.</i></p>
</details>


<h2 style="text-align: center;">Array Indexing and Slicing</h2>

<font size="4">Just like selecting specific cells or ranges in a spreadsheet, NumPy allows you to access subsets of your data using indexing.</font>

<h3>Accessing 1D Data (Vectors):</h3>

In [ ]:
# Imagine these are exam scores for 5 students
scores = np.array([85, 92, 78, 95, 88])

# Indexing (0-based counting)
first_score = scores[0]      # 85 (The first element)
last_score = scores[-1]      # 88 (Negative index counts from the end)

print(f"The first score is: {first_score}, the last score is: {last_score}")

# Slicing [start:stop]
# Note: The 'stop' index is exclusive (not included)!
first_three = scores[0:3]    # Returns indices 0, 1, 2 -> [85, 92, 78]
all_but_first = scores[1:]   # From index 1 to the end -> [92, 78, 95, 88]

print(f"The first three elements are: {first_three}\nAll elements except the first are: {all_but_first}")

<h3>Accessing 2D Data (Matrices):</h3>

<font size="4">The syntax is: `array[row_selector, column_selector]`.

In [ ]:
# A 3x3 matrix representing data
data = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])

# 1. Single Element: [Row, Column]
element = data[0, 1]         # Row 0, Col 1 -> Value is 2
print(f"1. To extract a single element, first select the row and then the column. For example, the second element of the first row: {element}")

# 2. Entire Row: [Row, :]
# The colon (:) means "select everything in this dimension"
first_row = data[0, :]       # Row 0, All columns -> [1, 2, 3]
print(f"2. This code extract all the elements in a row. For example we can select the first row: {first_row}")

# 3. Entire Column: [:, Column]
second_column = data[:, 1]   # All rows, Column 1 -> [2, 5, 8]
print(f"2. This code extract all the elements in a column. For example we can select the second column: {second_column}")

In [ ]:
# ---------------------------------------------------------
# EXERCISE 3: Indexing and Slicing
# ---------------------------------------------------------

# NOTE: This exercise relies on the 'anxiety_scores' array 
# from the previous exercises.

# 1. Extract the anxiety scores for Participant 3 across all time points.
#    Hint: Participant 3 is at row index 2. Use a colon : to select all columns.

# ... write your code here ...


# 2. Extract the scores for ALL participants at Time Point 2 
#    (the middle measurement, index 1).
#    Hint: Use a colon : to select all rows, and specify the column index.

# ... write your code here ...


# 3. Extract a sub-matrix containing scores for Participants 2-4 
#    at Time Points 1-2 (first two measurements).
#    Hint: Remember that slicing ranges [start:stop] are exclusive 
#    of the 'stop' index. 
#    - Participants 2, 3, 4 correspond to indices 1 to 4.
#    - Time points 1 and 2 correspond to indices 0 to 2.

# ... write your code here ...


# 4. Get the LAST participant's FINAL anxiety score using negative 
#    indexing for both dimensions.
#    Hint: Use -1 to access the last element of a dimension.

# ... write your code here ...


<details>
  <summary>Click here to see the solution 💡</summary>
  <br>
  <b> Solution:</b>
  <pre>
# Re-creating the array for context
anxiety_scores = np.array([
    [7, 6, 5],
    [8, 8, 7],
    [4, 3, 3],
    [9, 8, 6],
    [5, 5, 4]
])

<font size="2">**1. Participant 3 (All Timepoints)**</font>

<font size="2">Row index 2 represents Participant 3</font>
p3_scores = anxiety_scores[2, :]
print(f"Participant 3 scores: {p3_scores}")

<font size="2">**2. Time Point 2 (All Participants)**</font>
<font size="2">Column index 1 represents Time Point 2</font>
tp2_scores = anxiety_scores[:, 1]
print(f"Time Point 2 scores: {tp2_scores}")

<font size="2">**3. Sub-matrix (Participants 2-4, Time Points 1-2)**</font>
<font size="2">Rows 1:4 (indices 1, 2, 3) and Columns 0:2 (indices 0, 1)</font>
sub_matrix = anxiety_scores[1:4, 0:2]
print(f"Sub-matrix:\n{sub_matrix}")

<font size="2">**4. Last Participant, Final Score**</font>
<font size="2">Negative indexing for the last row and last column</font>
last_score = anxiety_scores[-1, -1]
print(f"Last score: {last_score}")
  </pre> 
  <br>
  <b>Expected Output:</b>
  <pre>
Participant 3 scores: [4 3 3]
Time Point 2 scores: [6 8 3 8 5]
Sub-matrix:
[[8 8]
 [4 3]
 [9 8]]
Last score: 4
  </pre>
  <p><i>Remember: Python slicing is <b>exclusive</b> at the end. To select participants 2, 3, and 4 (indices 1, 2, 3), we must slice <code>[1:4]</code>.</i></p>
</details>


<h3>Array Operations and Vectorization</h3>

<font size="4">One of NumPy's most powerful features is **vectorization**: the ability to apply mathematical operations to entire arrays at once, without writing loops. This is not only faster to write but computationally much more efficient.</font>

<h4>1. Arithmetic Operations:</h4>

In [ ]:
# Vectorized Math: Apply a formula to every element simultaneously
temperatures_c = np.array([15.2, 18.5, 21.1, 16.8, 14.5])

# Convert all to Fahrenheit in one line (No 'for' loop needed!)
temperatures_f = temperatures_c * 9/5 + 32 
print(f"We can convert a temperature from Celsius to Fahrenheit using the vectorisation feature, which returns an array {temperatures_f}")
# Result: [59.36, 65.3, 69.98, 62.24, 58.1]

# Element-wise Operations: Subtracting two arrays
scores_pre = np.array([75, 80, 85])
scores_post = np.array([78, 82, 88])

# Calculate improvement for each participant
improvement = scores_post - scores_pre  
# Result: [3, 2, 3] (78-75, 82-80, 88-85)

print(f"We can subtract two arrays simply by using: {scores_post} - {scores_pre}. This return an array of {improvement}")


<h4>2. Statistical Summaries:</h4>

<font size="4">NumPy has built-in functions to quickly summarize large datasets.</font>

In [ ]:
reaction_times = np.array([245, 250, 238, 255, 248])

# Measures of Central Tendency
mean_rt = np.mean(reaction_times)      # Average: 247.2
median_rt = np.median(reaction_times)  # Middle value: 248.0

print(f"The mean RT value is: {mean_rt}, while the median is: {median_rt}")

# Measures of Variability
std_rt = np.std(reaction_times)        # Standard Deviation: ~5.84
min_rt = np.min(reaction_times)        # Fastest RT: 238
max_rt = np.max(reaction_times)        # Slowest RT: 255

print(f"The Standard Deviation of the RTs is: {std_rt}\nThe fastest RT is: {min_rt}ms, the slowest is: {max_rt}ms")

In [ ]:
# ---------------------------------------------------------
# EXERCISE 4: Basic Operations and Vectorization
# ---------------------------------------------------------

# 1. Create an array of test scores: [72, 85, 90, 68, 78, 92, 88]

# ... write your code here ...


# 2. Calculate and print the mean, median, and standard deviation 
#    of these scores.
#    Hint: Use np.mean(), np.median(), and np.std().

# ... write your code here ...


# 3. Apply a "curve" to the exam by adding 5 points to every 
#    student's score.
#    Hint: In NumPy, you can add a single number to an entire array directly.

# ... write your code here ...


# 4. Calculate the difference between each student's original score 
#    and the group mean (i.e., score - mean).
#    Hint: Subtract the mean variable (scalar) from the scores array (vector).

# ... write your code here ...


# 5. Use np.clip(array, min_value, max_value) to ensure that no 
#    "curved" score exceeds 100.
#    Hint: Try adding 20 points to the original scores first to create some values > 100, then apply np.clip().

# ... write your code here ...


<details>
  <summary>Click here to see the solution 💡</summary>
  <br>
  <b> Solution:</b>
  <pre>
# 1. Create Data
scores = np.array([72, 85, 90, 68, 78, 92, 88])

<font size="2">**2. Descriptive Statistics**</font>
mean_score = np.mean(scores)
median_score = np.median(scores)
std_score = np.std(scores)

print(f"Mean: {mean_score:.2f}")
print(f"Median: {median_score}")
print(f"Standard Deviation: {std_score:.2f}")

<font size="2">**3. Vectorized Operations (Curving Grades)**</font>
curved_scores = scores + 5
print(f"\nCurved Scores (+5): {curved_scores}")

<font size="2">**4. Deviation from Mean**</font>
<font size="2">Subtracting a single scalar (mean) from the entire array</font>
deviations = scores - mean_score
print(f"Deviations from mean: {np.round(deviations, 3)}")

<font size="2">**5. Clipping Values**</font>
<font size="2">Pretend we added 20 points instead, pushing some over 100</font>
super_curve = scores + 20  
<font size="2">Force values to stay between 0 and 100</font>
final_scores = np.clip(super_curve, 0, 100)
print(f"Clipped Scores: {final_scores}")
  </pre> 
  <br>
  <b>Expected Output:</b>
  <pre>
Mean: 81.86
Median: 85.0
Standard Deviation: 8.63

Curved Scores (+5): [77 90 95 73 83 97 93]
Deviations from mean: [-9.9  3.1  8.1 -13.9 -3.9 10.1  6.1]
Clipped Scores: [ 92 100 100  88  98 100 100]
  </pre>
  <p><i><b>How np.clip works:</b> <code>np.clip(array, min, max)</code> acts like a ceiling and floor. Any value below <code>min</code> becomes <code>min</code>, and any value above <code>max</code> becomes <code>max</code>. In this example, scores like 105 or 110 were capped at 100.</i></p>
</details>


<h3>Reshaping and Combining Arrays</h3>

In [ ]:
# Transform array dimensions
data = np.array([1, 2, 3, 4, 5, 6])
matrix = data.reshape(2, 3)  # 2×3 matrix
# [[1, 2, 3],
#  [4, 5, 6]]
print(f"This is the original array (1D): {data}\nThe transormed shape in 2D: {matrix.shape}\n{matrix} ")

# Flatten back to 1D
flat = matrix.flatten()  # [1, 2, 3, 4, 5, 6]
print(f"We can reshape from 2D in 1D array by using the .flatten() method, obtaining again: {flat}")

In [ ]:
group1 = np.array([75, 80, 85])
group2 = np.array([78, 82, 88])

# Stack vertically (add rows)
all_groups = np.vstack([group1, group2])
print(f"The two array are stacked vertically:\n{all_groups}")

# Stack horizontally (add columns)
side_by_side = np.hstack([group1, group2])
print(f"The two array are stacked horizontally:\n{side_by_side}")

## You can do the same thing by using the np.concatenate() method. 
## In this case you need to pass the arrays as a tuple or list

group1 = np.array([[75, 80, 85]])
group2 = np.array([[78, 82, 88]])
# Concatenate along specific axis. The arrays must have the same shape.
combined_v = np.concatenate((group1, group2), axis = 0) 
combined_h = np.concatenate((group1, group2), axis = 1)
print(combined_v)
print(combined_h)

In [ ]:
# ---------------------------------------------------------
# EXERCISE 5: Reshaping and Combining Arrays
# ---------------------------------------------------------

# 1. Create a 1D array with values from 1 to 12.
#    Hint: Use np.arange(start, stop) to generate a sequence quickly.

# ... write your code here ...


# 2. Reshape it into a 3x4 array (3 participants, 4 trials).
#    Hint: Use the .reshape(rows, columns) method.

# ... write your code here ...


# 3. Create another 3x4 array with values from 13 to 24.
#    Hint: You can chain np.arange() and .reshape() in one line.

# ... write your code here ...


# 4. Combine both arrays vertically to represent 6 participants total.
#    Hint: Use np.vstack([array1, array2]) OR np.concatenate((a1, a2), axis=0).

# ... write your code here ...


# 5. Extract all data from trial 3 (column index 2) for ALL participants 
#    in the combined array.
#    Hint: Use slicing [row_start:row_end, col_index].

# ... write your code here ...


<details>
  <summary>Click here to see the solution 💡</summary>
  <br>
  <b> Solution:</b>
  <pre>
      
<font size="2">**1. Creating and Reshaping Data**</font>
<font size="2">Create 1D array from 1 to 12</font>
data_part1 = np.arange(1, 13)
print(data_part1)

<font size="2">**Reshape into 3 participants x 4 trials**</font>
matrix_part1 = data_part1.reshape(3, 4)
print(f"Matrix 1 (Participants 1-3):\n{matrix_part1}")

<font size="2">**2. Creating Second Dataset**</font>
<font size="2">Create and reshape in one step</font>
matrix_part2 = np.arange(13, 25).reshape(3, 4)
print(f"\nMatrix 2 (Participants 4-6):\n{matrix_part2}")

<font size="2">**3. Combining Arrays (Vertical Stack)**</font>
<font size="2">Stacking vertically to increase number of participants</font>
combined_data = np.vstack([matrix_part1, matrix_part2])
<font size="2">Alternative: np.concatenate((matrix_part1, matrix_part2), axis=0)</font>
print(combined_data)
print(f"\nCombined Data Shape: {combined_data.shape}")

<font size="2">**4. Extracting Specific Trial Data**</font>
<font size="2">Extract Trial 3 (Index 2) for ALL participants (:)</font>
trial_3_data = combined_data[:, 2]
print(f"\nTrial 3 Data (All Participants): {trial_3_data}")
  </pre> 
  <br>
  <b>Expected Output:</b>
  <pre>
Matrix 1 (Participants 1-3):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix 2 (Participants 4-6):
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

Combined Data Shape: (6, 4)

Trial 3 Data (All Participants): [ 3  7 11 15 19 23]
  </pre>
  <p><i><b>Tip:</b> <code>np.arange(start, stop)</code> generates numbers up to, but <b>not including</b>, the stop value. So <code>np.arange(1, 13)</code> gives numbers 1 through 12.</i></p>
</details>


<h3>Boolean Indexing and Filtering</h3>

<h4>Conditional Selection:</h4>

In [ ]:
scores = np.array([65, 75, 85, 55, 95, 70])

# ----------------------------------------------------------
# 1. Boolean Mask (Creating True/False Array)
# ----------------------------------------------------------
# A boolean mask is an array of True/False values that matches 
# the shape of your data
passed = scores >= 70  
print(f"Boolean Mask (Passed?): {passed}")
# Output: [False  True  True False  True  True]

# ----------------------------------------------------------
# 2. Filtering Data (Selecting Only Certain Values)
# ----------------------------------------------------------
# Use the boolean mask to extract only the scores that meet the condition
passing_scores = scores[scores >= 70]  
print(f"Passing Scores: {passing_scores}")
# Output: [75 85 95 70]

# ----------------------------------------------------------
# 3. Multiple Conditions: AND (&)
# ----------------------------------------------------------
# Select scores that satisfy BOTH conditions simultaneously
# Example: Scores >= 70 AND < 90 (good but not excellent)
good_scores = scores[(scores >= 70) & (scores < 90)]  
print(f"Good Scores (70-89): {good_scores}")
# Output: [75 85 70]

# ----------------------------------------------------------
# 4. Multiple Conditions: OR (|)
# ----------------------------------------------------------
# Select scores that satisfy AT LEAST ONE condition
# Example: Either very low (<60) OR very high (>90)
extreme_scores = scores[(scores < 60) | (scores > 90)]
print(f"Extreme Scores: {extreme_scores}")
# Output: [55 95]

# ----------------------------------------------------------
# 5. Counting How Many Meet Criteria
# ----------------------------------------------------------
# np.sum() treats True as 1 and False as 0, so it counts True values
n_passed = np.sum(scores >= 70)  
print(f"Number of Passing Scores: {n_passed}")
# Output: 4

# Alternative: Get the percentage
percent_passed = (n_passed / len(scores)) * 100
print(f"Percentage Passed: {percent_passed:.1f}%")
# Output: 66.7%


In [ ]:
# ---------------------------------------------------------
# EXERCISE 6: Boolean Indexing and Data Cleaning
# ---------------------------------------------------------

# 1. Create an array of reaction times (in ms):
#    Data: [245, 520, 238, 456, 255, 890, 248, 310, 275]

# ... write your code here ...


# 2. Create a boolean mask for "normal" reaction times.
#    Definition of normal: between 200 ms AND 400 ms (inclusive).
#    Hint: Combine two conditions using & and parentheses (cond1) & (cond2).

# ... write your code here ...


# 3. Filter the array to show ONLY the normal reaction times.
#    Hint: Use the mask inside the square brackets: array[mask]

# ... write your code here ...


# 4. Calculate the percentage of trials that were "normal".
#    Hint: np.sum(mask) counts the True values. Divide by total trials * 100.

# ... write your code here ...


# 5. Replace outliers (values > 400 ms) with the median of the 
#    NORMAL reaction times using np.where().
#    Hint: First calculate the median of the filtered array from step 3.
#    Then use np.where(condition, value_if_true, value_if_false).

# ... write your code here ...


<details>
  <summary>Click here to see the solution 💡</summary>
  <br>
  <b> Solution:</b>
  <pre>
# 1. Create Data
reaction_times = np.array([245, 520, 238, 456, 255, 890, 248, 310, 275])

<font size="2">**2. Boolean Mask (Normal RTs)**</font>
<font size="2">Combined condition: (RT >= 200) AND (RT <= 400) Don't forget parentheses around each condition!</font>
mask_normal = (reaction_times >= 200) & (reaction_times <= 400)
print(f"Normal RT Mask: {mask_normal}")

<font size="2">**3. Filtering Data**</font>
normal_rts = reaction_times[mask_normal]
print(f"Normal RTs only: {normal_rts}")

<font size="2">**4. Percentage Calculation**</font>
<font size="2">np.sum() counts the number of True values in the mask</font>
n_normal = np.sum(mask_normal)
total_trials = len(reaction_times)
percentage = (n_normal / total_trials) * 100
print(f"Percentage normal trials: {percentage:.1f}%")

<font size="2">**5. Replacing Outliers (Imputation)**</font>
<font size="2">Calculate median of only the GOOD data first</font>
median_normal = np.median(normal_rts)
print(f"Median of normal RTs: {median_normal}")

<font size="2">**Syntax: np.where(condition, value_if_true, value_if_false)**
<font size="2">We want: IF it's an outlier (>400), replace with median, ELSE keep original</font>

cleaned_data = np.where(reaction_times > 400, median_normal, reaction_times)
print(f"Cleaned Data: {cleaned_data}")
  </pre> 
  <br>
  <b>Expected Output:</b>
  <pre>
Normal RT Mask: [ True False  True False  True False  True  True  True]
Normal RTs only: [245 238 255 248 310 275]
Percentage normal trials: 66.7%
Median of normal RTs: 251.5
Cleaned Data: [245.  251.5 238.  251.5 255.  251.5 248.  310.  275. ]
  </pre>
  <p><i><b>Tip:</b> <code>np.where()</code> is incredibly useful for cleaning data. It reads like an "If-Else" statement applied to the entire array at once. Note that replacing integers with a float median (like 251.5) will automatically convert the whole array to float type.</i></p>
</details>


<h3>Working with Random Data (Simulation)</h3>

<h4>Random Number Generation</h4>

<font size="4">Simulation is a critical skill in modern psychology. Whether you are pre-registering a study, running a power analysis, or testing a new statistical model, you often need to generate "fake" data that behaves like real data.</font>

<font size="4">The Key to Science: Reproducibility (`np.random.seed`)</font>

<font size="4">Computers cannot generate truly random numbers; they generate pseudo-random sequences.</font>

- <font size="4">If you run np.random.normal() twice, you get different numbers.</font>

- <font size="4">If you set a seed (e.g., np.random.seed(42)), you force the computer to start its random sequence from a fixed point.</font>

- <font size="4">Why do this? It ensures that every time you (or another researcher) run your code, you get the exact same "random" results. This is essential for debugging and sharing reproducible research.</font>

In [ ]:
# 1. ALWAYS set the seed first!
np.random.seed(42)

# 2. Random Integers (e.g., Participant IDs)
# Generate 20 IDs between 100 (inclusive) and 200 (exclusive)
participant_ids = np.random.randint(low=100, high=200, size=20)
print(participant_ids)

# 3. Uniform Distribution (Flat distribution)
# Useful for p-values, reaction times where any value is equally likely
# Generate 30 scores between 0 and 100
random_scores = np.random.uniform(low=0, high=100, size=30)
print(random_scores)

# 4. Normal Distribution (Gaussian/Bell Curve)
# The most common distribution in psychology (IQ, height, survey scores)
# Generate 50 IQ scores with Mean=100 and SD=15
iq_scores = np.random.normal(loc=100, scale=15, size=50)
print(iq_scores)

# 5. Random Categorical Choice
# Assign participants to experimental conditions
conditions = np.random.choice(['Control', 'Treatment'], size=40)
print(conditions)

In [ ]:
# ---------------------------------------------------------
# EXERCISE 7: Simulating Data and Randomness
# ---------------------------------------------------------

# 1. Set the random seed to 123 to ensure reproducibility.
#    Hint: Use np.random.seed().

# ... write your code here ...


# 2. Generate simulated depression scores for 100 participants 
#    drawn from a normal distribution with mean=15 and std=5.
#    Hint: Use np.random.normal(loc=..., scale=..., size=...).

# ... write your code here ...


# 3. Depression scores cannot be negative! Use np.clip() to ensure 
#    the minimum value is 0.
#    Hint: Use np.clip(array, min, max). You can use a high number (e.g. 50) for max. Print the first five results.

# ... write your code here ...


# 4. Calculate how many participants have a score strictly greater 
#    than 20 (indicating clinical significance).
#    Hint: Create a boolean condition (scores > 20) and sum it.

# ... write your code here ...


# 5. Generate a random list of group assignments for these 100 
#    participants, choosing randomly between 'Therapy', 'Medication', 
#    and 'Control'.
#    Hint: Use np.random.choice(list_of_options, size=...). Print the first five results.

# ... write your code here ...


# 6. REFLECTION QUESTION: 
#    How would the results change if you set the seed to 999 instead of 123?
#    Try changing the seed above and re-running the cell to see what happens!

<details>
  <summary>Click here to see the solution 💡</summary>
  <br>
  <b> Solution:</b>
  <pre>
<font size="2">**1. Setting the Seed**</font>
np.random.seed(123)

<font size="2">**2. Generating Depression Scores**</font>
<font size="2">Draw from normal distribution (mean=15, std=5)</font>
raw_scores = np.random.normal(15, 5, 100)

<font size="2">**3. Cleaning Data (Clipping)**</font>
<font size="2">Ensure no scores are below 0; max score can go up to 50</font>
clean_scores = np.clip(raw_scores, 0, 50)
print(f"First 5 clean scores: {np.round(clean_scores[:5], 2)}")

<font size="2">**4. Clinical Significance**</font>
<font size="2">Count how many scores are strictly greater than 20</font>
n_clinical = np.sum(clean_scores > 20)
print(f"Participants with clinical depression scores: {n_clinical}")

<font size="2">**5. Random Group Assignment**</font>
groups = np.random.choice(['Therapy', 'Medication', 'Control'], size=100)
print(f"First 5 assignments: {groups[:5]}")

<font size="2">**6. REFLECTION**</font>
<font size="2">If you change the seed to 999, you will get a DIFFERENT 
set of 100 scores and different group assignments. 
The "randomness" is determined entirely by the starting seed.</font>
  </pre> 
  <br>
  <b>Expected Output np.random.seed(123):</b>
  <pre>
First 5 clean scores: [ 9.57 19.99 16.41  7.47 12.11]
Participants with clinical depression scores: 24
First 5 assignments: ['Medication' 'Medication' 'Therapy' 'Control' 'Medication']
  </pre>
  <b>Expected Output np.random.seed(999):</b>
  <pre>
First 5 clean scores: [15.64 22.01 16.57 10.71 13.67]
Participants with clinical depression scores: 22
First 5 assignments: ['Control' 'Control' 'Medication' 'Therapy' 'Control']
  </pre>
  <p><i><b>Why use seeds?</b> In scientific research, reproducibility is everything. By sharing your code with <code>np.random.seed(123)</code>, another researcher on a different computer will generate the exact same "random" patients you did, allowing them to verify your analysis perfectly.</i></p>
</details>


<h3>Saving and Loading Data (Binary)</h3>

<font size="4">While Pandas is preferred for CSV/Excel files, NumPy has its own optimized binary format (`.npy`) which is incredibly fast and preserves data types perfectly. This is useful for saving pre-processed data (e.g., cleaned EEG signal matrices) to share with colleagues.<font>

In [ ]:
# Save a single array
data_matrix = np.random.rand(1000, 1000)
np.save('experiment_data.npy', data_matrix)

In [ ]:
# Load it back
loaded_data = np.load('experiment_data.npy')
print(loaded_data)

<h1 style="text-align: center;">Pandas 🐼</h1>

<font size="4">**Pandas** is the primary Python library for working with structured, tabular data such as spreadsheets and CSV files commonly used in psychology research. Built on top of NumPy, Pandas provides powerful tools for loading datasets, cleaning data, performing group-level analyses, and preparing data for statistical testing.<font>

<font size="4">**What is Pandas and Why Use It?**<font>
<font size="4">While NumPy excels at numerical array operations, Pandas is designed specifically for working with labeled, heterogeneous data. In psychology studies, you typically have datasets with mixed data types: participant IDs (integers), condition labels (strings), questionnaire responses (integers), and pshysiological data (floats) all in one table. Pandas handles this naturally through its core data structure: the **DataFrame**.<font>

<font size="4">For comprehensive tutorials and practice problems, visit the  [official Pandas documentation](https://pandas.pydata.org/docs/).<font>

<h3>Installing and Importing Pandas</h3>

<font size="4">Pandas is an external library, so, as you did for Numpy, you need to import it at the beginning of your script or notebook<font>

In [ ]:
import pandas as pd
import numpy as np  # Often used alongside Pandas

<h3>Core Data Structures in Pandas: Series and DataFrame</h3>
<font size="4">Pandas is built on two fundamental objects:</font>

- <font size="4">**Series**: 1D labeled array</font>
- <font size="4">**DataFrame**: 2D labeled data structure</font>

<font size="4">A Series is a one-dimensional labeled array.</font>

<font size="4">**Structure**: It has two main components: the Values (the data) and the Index (the labels/row numbers).</font>

<font size="4">**Data Type**: A Series usually contains data of one specific type (e.g., all integers).</font>

In [ ]:
# A Series representing IQ scores
iq_series = pd.Series([105, 112, 98, 120])
print(iq_series)
iq_series.iloc[1] # To extract the position based on index
type(iq_series)

<font size="4">A DataFrame is a two-dimensional labeled data structure.</font>

<font size="4">**Structure**: It is a collection of multiple Series arranged side-by-side. It has both Row labels (Index) and Column labels (Headers).</font>

<font size="4">**Data Type**: It is heterogeneous, meaning one column can be integers (Age), another floats (Reaction Time), and another strings (Gender).</font>

In [ ]:
# Example: Small pilot study with 4 participants
data = {
    'participant_id': [101, 102, 103, 104],
    'age': [22, 25, 23, 28],
    'condition': ['control', 'treatment', 'treatment', 'control'],
    'score': [75, 82, 88, 70]
}

df = pd.DataFrame(data)
print(df)

import openpyxl

## Save the DataFrame in .csv and .xlsx files
df.to_csv('participants_data.csv', index=False) # Index = False prevent Pandas saving the Index as a column
df.to_excel('participants_data.xlsx', sheet_name='Pilot_Data', index=False)

In [ ]:
# ---------------------------------------------------------
# EXERCISE 1: Creating Your First DataFrame
# ---------------------------------------------------------

# 1. Create a DataFrame representing 6 participants in a Stroop task.
#    Use the following data:
#    - participant_id: [1, 2, 3, 4, 5, 6]
#    - age: [20, 22, 19, 24, 21, 23]
#    - gender: ['F', 'M', 'F', 'F', 'M', 'M']
#
#    For the Reaction Times, use np.random.randint():
#    - congruent_rt: 6 random integers between 500 and 600
#    - incongruent_rt: 6 random integers between 650 and 800
#    (Don't forget to set a seed like np.random.seed(42) first!)
#
#    Hint: Create a dictionary first (keys = column names), 
#    then pass it to pd.DataFrame().

# ... write your code here ...


# 2. Print the DataFrame to see its structure.

# ... write your code here ...


# 3. Add a new column called 'stroop_effect'.
#    This should calculate the difference: incongruent_rt - congruent_rt.
#    Hint: Access columns like df['col_name'] and subtract them directly.

# ... write your code here ...

# 4. Save the new DataFrame in .csv and .xlsx formats with the name: pd_exercise_1.
#    Hint: use the dataframe_name.to_csv() and dataframe_name.to_excel() methods.

# ... write your code here ...


<details>
  <summary>Click here to see the solution 💡</summary>
  <br>
  <b> Solution:</b>
  <pre>
import pandas as pd
import numpy as np
import openpyxl

<font size="2">Set seed for reproducibility</font>
np.random.seed(42)

<font size="2">**1. Creating the Dictionary**</font>
data = {
    'participant_id': [1, 2, 3, 4, 5, 6],
    'age': [20, 22, 19, 24, 21, 23],
    'gender': ['F', 'M', 'F', 'F', 'M', 'M'],
    'congruent_rt': np.random.randint(500, 600, 6),   # Random Congruent RTs
    'incongruent_rt': np.random.randint(650, 800, 6)  # Random Incongruent RTs
}

<font size="2">**2. Creating the DataFrame**</font>
df = pd.DataFrame(data)

<font size="2">**3. Calculating the Stroop Effect**</font>
<font size="2">Vectorized subtraction: (Incongruent - Congruent)</font>
df['stroop_effect'] = df['incongruent_rt'] - df['congruent_rt']
print("Final DataFrame:")
print(df)

<font size="2">**4. Saving the DataFrame**</font>
df.to_csv("pd_exercise_1.csv", index=False)
df.to_excel("pd_exercise_1.xlsx", sheet_name='exercise_1', index=False)
  </pre> 
  <br>
  <b>Expected Output (with seed=42):</b>
  <pre>
Final DataFrame:
   participant_id  age gender  congruent_rt  incongruent_rt  stroop_effect
0               1   20      F           551             752            201
1               2   22      M           592             771            179
2               3   19      F           514             724            210
3               4   24      F           571             737            166
4               5   21      M           560             766            206
5               6   23      M           520             749            229
  </pre>
  <p><i><b>Tip:</b> In Pandas, mathematical operations are "vectorized" just like in NumPy. When we write <code>df['incongruent_rt'] - df['congruent_rt']</code>, Pandas automatically understands to subtract row 1 from row 1, row 2 from row 2, and so on.</i></p>
</details>


<h3>Loading Real Data from Files</h3>

<font size="3">**Reading CSV Files**<font> 

In [ ]:
# Load a CSV file
df = pd.read_csv('pd_exercise_1.csv')

# Common parameters:
df = pd.read_csv('pd_exercise_1.csv', 
                 sep=',',           # Delimiter (default is comma)
                 header=0,          # Row number to use as column names
                 index_col=0,       # Column to use as row labels
                 na_values=['NA', 'missing'])  # Values to treat as NaN
print(f"The DataFrame has been loaded succesfully:\n {df.head()}")

<font size="3">**Reading Excel Files**<font> 

In [ ]:
# Load an Excel file (requires openpyxl library)
df = pd.read_excel('pd_exercise_1.xlsx', sheet_name='exercise_1')
print(f"The DataFrame has been loaded succesfully:\n {df.head()}")

<h3>Inspecting Your Data</h3>

<font size="4">After loading data, you should always inspect it to catch errors immediately (e.g., incorrect column names or missing values).<font>

<font size="4">There are some fundamental methods that you should know to inspect the DataFrame carefully and effortless<font>

<font size="4">**Quick Previews**</font>

<font size="4">Usually methods for this purpose are: `df.head()` and `df.tail()`. Both can accept an integer inside the function to display the corresponding number of rows. For example `df.head(10)` will display the first 10 rows of the DataFrame.  

In [ ]:
# View the first 5 rows (Standard sanity check)
print(f"Print the first 5 rows:\n {df.head()}")  

# View the last 3 rows (Check if the file ended correctly)
print(f"Print the last 3 rows:\n {df.tail(3)}") 

<font size="4">**Structural Information**</font>

<font size="4">These attributes give you a "high-level" view of your dataset's architecture without showing the actual data.</font>

- <font size="4">`df.shape`: **The Dimensions**
<font size="4">Returns a simple tuple (rows, columns). It's the first thing you check to see if your data loaded correctly (e.g., "Did I get all 100 participants?").</font>
- <font size="4">`df.columns`: **The Headers**
<font size="4">Returns a list of all column names. This is incredibly useful for copying and pasting exact names into your code to avoid KeyError typos (e.g., misspellings like "ReactionTime" vs. "reaction_time").</font>
- <font size="4">`df.dtypes`: **The Data Types**
<font size="4">Returns a list showing the storage type of each column. This helps you spot "invisible" errors, like a reaction time column being stored as text (object) instead of numbers (float) because of a typo in the raw file. Common types are:  int64 (Integers), float64 (Decimals), object (Text/Strings).</font>

In [ ]:
# Dimensions: Returns (Rows, Columns)
print(f"My DataFrame has: {df.shape[0]} participants, and {df.shape[1]} variables.")  

print("*"*100)
# Column Names: Returns a list-like object of headers
# Useful for copy-pasting column names to avoid typos
print(df.columns.to_list())  

print("*"*100)
# Data Types: Shows the type of data in each column
# int64 (Integers), float64 (Decimals), object (Text/Strings)
print(df.dtypes)   

print("*"*100)

<font size="4">**Comprehensive Summaries**</font>

<font size="4">These methods generate reports to help you understand the quality and distributions of your data.</font>

- <font size="4">`df.info()`: **The "Full Scan"**</font>
<font size="4">This is the most critical diagnostic tool. It combines shape, dtypes, and—most importantly—non-null counts into one report.</font>

<font size="4">Why use it? It’s the fastest way to spot missing data. If your dataset has 100 rows but the 'Age' column shows "95 non-null", you immediately know you have 5 missing values to handle.</font>

- <font size="4">`df.describe()`: **The "Report"**</font>
<font size="4">Automatically calculates summary statistics for all numerical columns.</font>

<font size="4">What it shows: Count, Mean, Standard Deviation (std), Min, Quartiles (25%, 50%, 75%), and Max.</font>

<font size="4">Why use it? To sanity-check your data. For example, if the min age is -5 or the max score is 1000 on a 1-10 scale, you know you have data entry errors to fix.</font>

In [ ]:
# Shows non-null counts and data types for every column
# CRITICAL for spotting missing data (NaNs)
df.info()   

print("*"*100)
# The "Report Card": Generates descriptive stats for numerical columns
# (Count, Mean, Std, Min, 25%, 50%, 75%, Max)
df.describe() 


<font size="4">**Selecting and Accessing Data**</font>

<font size="4">In Pandas, there are specific rules for selecting data. The most important distinction is between selecting by **Label (names)** vs. selecting by **Position (integer index)**.</font>

<h3>Accessing Columns</h3>
    
- <font size="4">`df['column_name']`: to access one column.</font>
- <font size="4">`df[['column_name_1', 'column_name_2']]`: to access multiple columns. ⚠️ Note the double brackets!</font>

<h3>Accessing Rows</h3>

- <font size="4">`.iloc` as "Integer LOCation". It behaves exactly like NumPy array indexing. You use integers to specify row and column numbers (0, 1, 2...).</font>
- <font size="4">`.loc`as "LOCation by name". You use the actual names of the rows (index labels) and columns. This is more readable and safer for data analysis.</font>


In [ ]:
# Select a SINGLE column -> Returns a Series (1D)
ages = df['age']

print(ages)

print("*"*100)

# Select MULTIPLE columns -> Returns a DataFrame (2D)
demographics = df[['participant_id', 'age', 'gender']]
print(demographics)


In [ ]:
# Select the FIRST row (at index 0)
first_participant = df.iloc[0]

# Select the first 3 rows
# Remember: Python slicing [start:stop] is exclusive of the end!
first_three = df.iloc[0:3]

# Select a subset: First 5 rows (0-4) and columns 1 to 2
# Structure: df.iloc[rows, columns]
subset = df.iloc[0:5, 1:3]

In [ ]:
# Select rows where the index label is 0
# (If your index is default 0-100, this looks like iloc, but logic differs)
participant_0 = df.loc[0]
print(participant_0)
print("*"*100)

# Select specific rows and SPECIFIC NAMED columns
# "Give me rows 0 to 4 for the 'age' and 'stroop_effect' columns"
# Note: unlike iloc, .loc slicing includes the end label (0:4 includes 4)
subset = df.loc[0:4, ['age', 'stroop_effect']]
print(subset)
print("*"*100)

# Boolean Selection (Most Powerful Feature)
# "Select all rows LOCATED WHERE age is less than 25"
young_participants = df.loc[df['age'] < 25]
print(f"You can select all rows LOCATED WHERE age is less than 25:\n {young_participants}")


<font size="4">**Summary**</font>

| <font size="4">Method</font>    | <font size="4">Stands For</font>       | <font size="4">Inputs</font>                 | <font size="4">Slicing Behavior</font>              |
| --------- | ---------------- | ---------------------- | ----------------------------- |
| <font size="4">df.iloc[]</font> | <font size="4">Integer Location</font> | <font size="4">Integers (0, 1, 2)</font>     | <font size="4">Exclusive (0:3 -> 0, 1, 2)</font>    |
| <font size="4">df.loc[]</font>  | <font size="4">Label Location</font>   | <font size="4">Names ('age', 'score')</font> | <font size="4">Inclusive (0:3 -> 0, 1, 2, 3)</font> |

In [ ]:
# ---------------------------------------------------------
# EXERCISE 2: Selecting and Filtering Data
# ---------------------------------------------------------

# NOTE: This exercise relies on the 'df' DataFrame you created 
# in Exercise 1 (Stroop Task).

# 1. Select only the 'age' column and calculate its mean.
#    Hint: Access the column like df['col_name'] and use .mean().

# ... write your code here ...


# 2. Select all rows where age is greater than 21.
#    Hint: Use Boolean Indexing -> df[condition].

# ... write your code here ...


# 3. Select 'participant_id', 'gender', and 'stroop_effect' columns 
#    for participants with a Stroop effect > 160ms.
#    Hint: Combine filtering (rows) and column selection.
#    df.loc[condition, ['col1', 'col2', ...]]

# ... write your code here ...


# 4. Use .iloc to select the 2nd through 4th participants (indices 1-3).
#    Hint: Remember that standard Python slicing [start:stop] is exclusive.

# ... write your code here ...


# 5. Calculate the correlation between 'age' and 'stroop_effect'.
#    Hint: Select the two columns first, then apply .corr().

# ... write your code here ...

<details>
  <summary>Click here to see the solution 💡</summary>
  <br>
  <b> Solution:</b>
  <pre>
      
<font size="2">**1. Average Age**</font>
<font size="2">Select 'age' column and compute mean</font>
mean_age = df['age'].mean()
print(f"Mean Age: {mean_age:.2f}")

<font size="2">**2. Filtering Rows (Age > 21)**</font>
<font size="2">Simple boolean indexing</font>
older_participants = df[df['age'] > 21]
print(f"\nParticipants > 21 years:\n{older_participants}")

<font size="2">**3. Complex Selection (Condition + Specific Columns)**</font>
<font size="2">Use .loc[row_condition, column_names]</font>
high_stroop = df.loc[df['stroop_effect'] > 160, ['participant_id', 'gender', 'stroop_effect']]
print(f"\nHigh Stroop Effect Participants:\n{high_stroop}")

<font size="2">**4. Positional Selection (.iloc)**</font>
<font size="2">Indices 1, 2, 3 (The 'stop' index 4 is exclusive)</font>
subset_iloc = df.iloc[1:4]
print(f"\nParticipants 2 to 4 (Indices 1-3):\n{subset_iloc}")

<font size="2">**5. Correlation**</font>
<font size="2">Calculate correlation matrix for the two specific variables</font>
corr_matrix = df[['age', 'stroop_effect']].corr()
print(f"\nCorrelation Matrix:\n{corr_matrix}")
  </pre> 
  <br>
  <b>Expected Output:</b>
  <pre>
Mean Age: 21.50

Participants > 21 years:
   participant_id  age gender  congruent_rt  incongruent_rt  stroop_effect
1               2   22      M           592             771            179
3               4   24      F           571             737            166
5               6   23      M           520             749            229

High Stroop Effect Participants:
   participant_id gender  stroop_effect
0               1      F            201
1               2      M            179
2               3      F            210
3               4      F            166
4               5      M            206
5               6      M            229

Participants 2 to 4 (Indices 1-3):
   participant_id  age gender  congruent_rt  incongruent_rt  stroop_effect
1               2   22      M           592             771            179
2               3   19      F           514             724            210
3               4   24      F           571             737            166

Correlation Matrix:
                    age  stroop_effect
age            1.000000      -0.384939
stroop_effect -0.384939       1.000000
  </pre>
  <p><i><b>Note on Correlation:</b> The <code>.corr()</code> method computes the pairwise correlation (Pearson by default). The diagonal is always 1.0 (correlation of a variable with itself). The off-diagonal values show the relationship between your variables.</i></p>
</details>


<h3>Filtering Data with Boolean Indexing</h3>

<font size="4">Filtering allows you to create subsets of your data based on specific criteria (e.g., "Show me only the participants who passed the attention check").</font>

<font size="4">**1. Single Condition**

<font size="4">To filter, we put a boolean expression inside the DataFrame's square brackets `df[...]`.

<font size="4">**2. Multiple Conditions**
<font size="4">In Pandas, you cannot use the standard Python keywords and / or. Instead, you must use bitwise operators:

- <font size="4">AND: Use `&` (Both conditions must be True)
- <font size="4">OR: Use `|` (At least one condition must be True)
- <font size="4">NOT: Use `~` (Invert the condition)

<font size="4">**CRITICAL RULE**: You must wrap each individual condition in parentheses (). Correct: (df['age'] < 25) & (df['score'] > 80)</font>

In [ ]:
data = {
    'age': [22, 25, 30, 21, 28, 24, 35, 19],
    'condition': ['treatment', 'control', 'treatment', 'treatment', 'control', 'treatment', 'control', 'control'],
    'score': [85, 62, 78, 91, 55, 88, 70, 45]
}

df = pd.DataFrame(data)

# Select participants in the 'treatment' group
treatment_group = df[df['condition'] == 'treatment']
print(treatment_group)

print("*"*100)

# Select participants with scores above 80
high_performers = df[df['score'] > 80]
print(high_performers)

In [ ]:
# AND: Young participants in the control group
young_treatment = df[(df['age'] < 25) & (df['condition'] == 'control')]
print(young_treatment)
print("*"*100)

# OR: Participants with extreme ages (below 20 OR above 30)
extreme_ages = df[(df['age'] < 20) | (df['age'] > 30)]
print(extreme_ages)
print("*"*100)

# NOT: Participants who are NOT in the treatment group
not_control = df[~(df['condition'] == 'treatment')]
print(not_control)
print("*"*100)

In [ ]:
# ---------------------------------------------------------
# EXERCISE 3: Filtering Data with Boolean Logic
# ---------------------------------------------------------

# 1. Create a DataFrame for 12 participants.
#    Columns:
#    - 'id': numbers 1 to 12
#    - 'age': random integers 18-35
#    - 'group': random choice of ['A', 'B', 'C']
#    - 'anxiety_score': random integers 1-10
#    - 'depression_score': random integers 1-10
#    (Remember to set np.random.seed(42)!)

# ... write your code here ...


# 2. Filter for participants in Group 'A' OR Group 'B'.
#    Hint: Use the bitwise OR operator (|). Don't forget parentheses!

# ... write your code here ...


# 3. Filter for "High Comorbidity": 
#    anxiety_score > 7 AND depression_score > 6.
#    Hint: Use the bitwise AND operator (&).

# ... write your code here ...


# 4. Filter for "Resilient Youth": 
#    Participants younger than 25 AND anxiety_score < 5.

# ... write your code here ...


# 5. Count and print how many participants were found in each step.
#    Hint: use .shape[0] or len(filtered_df).

# ... write your code here ...


<details>
  <summary>Click here to see the solution 💡</summary>
  <br>
  <b> Solution:</b>
  <pre>
      
<font size="2">**1. Creating the DataFrame**</font>
np.random.seed(42)

df = pd.DataFrame({
    'id': np.arange(1, 13),
    'age': np.random.randint(18, 36, 12),
    'group': np.random.choice(['A', 'B', 'C'], 12),
    'anxiety_score': np.random.randint(1, 11, 12),
    'depression_score': np.random.randint(1, 11, 12)
})

<font size="2">**2. OR Filter (Group A | B)**</font>
<font size="2">Don't forget parentheses around each condition!</font>
group_ab = df[(df['group'] == 'A') | (df['group'] == 'B')]
print(f"Participants in Group A or B: {group_ab.shape[0]}")

<font size="2">**3. AND Filter (High Comorbidity)**</font>
<font size="2">Both scores must be high</font>
comorbid = df[(df['anxiety_score'] > 7) & (df['depression_score'] > 6)]
print(f"High Comorbidity Cases: {len(comorbid)}")

<font size="2">**4. Mixed Filter (Resilient Youth)**</font>
<font size="2">Age < 25 AND Anxiety < 5</font>
resilient = df[(df['age'] < 25) & (df['anxiety_score'] < 5)]
print(f"Resilient Youth Cases: {len(resilient)}")

<font size="2">**Preview of Resilient Group:**</font>
print(resilient)
  </pre> 
  <br>
  <b>Expected Output (with seed=42):</b>
  <pre>
Participants in Group A or B: 10
High Comorbidity Cases: 2
Resilient Youth Cases: 1
   id  age group  anxiety_score  depression_score
7   8   21     A              3                 5
  </pre>
  <p><i><b>Important:</b> In Python, logical operators follow a strict order of operations. The parentheses <code>(df['age'] < 25)</code> ensure that the comparison happens <b>before</b> the <code>&</code> operator tries to combine the results. Without them, you would get a <code>TypeError</code>.</i></p>
</details>


<font size="4">**Adding, Modifying, and Removing Columns**</font>

<font size="4">Data manipulation is the heart of analysis. You often need to create new variables (e.g., total scores), recode existing ones (e.g., ms to seconds), or remove identifiers before sharing data.

<font size="4">**1. Adding New Columns**</font>

<font size="4">You can create a new column simply by assigning a value to a new column name like `df['new_col'] = ....`</font>

In [ ]:
#import pandas as pd
#import numpy as np
# Set seed for reproducibility
np.random.seed(42)

# Create the initial data dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'Surname': ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis', 'Rodriguez', 'Martinez'],
    'pre_score': np.random.randint(50, 80, 10),      # Random scores 50-79
    'post_score': np.random.randint(70, 100, 10),    # Random scores 70-99
    'attention_score': np.random.randint(60, 100, 10) # Attention check scores
}

# Create DataFrame
df = pd.DataFrame(data)

# 1. From Calculation (Vectorized Math)
# Calculates row-by-row automatically
df['improvement'] = df['post_score'] - df['pre_score']

# 2. From Boolean Logic (True/False)
df['passed_check'] = df['attention_score'] >= 80

# 3. Constant Value (Assigns same string/number to EVERY row)
df['study_version'] = 'Pilot_v1'

df.head(10)

<font size="4">**2. Modifying Columns**</font>

<font size="4">The `lambda` function (or "anonymous function") is a one-line function that you define without a name. Unlike standard functions defined with def, lambda functions are used for short, simple operations that you likely won't need to reuse elsewhere.

<font size="4">The syntax of this kind of functions is:

<font size="4">`lambda arguments: expression`

- <font size="4">**lambda**: The keyword that starts the definition.

- <font size="4">**arguments**: The input variable(s) (just like inputs in a normal function).

- <font size="4">**Separator** (:) between arguments and logic.

- <font size="4">**expression**: The single calculation or operation to perform. It automatically returns the result (no return keyword needed).

<font size="4">The most powerful use case is with `df.apply()` in Pandas, where you need to pass a function as an argument to transform a column row-by-row.

In [ ]:
# 1. Modifying numerical columns (Vectorized Math)
# Example: Convert 'improvement' score to a percentage of the pre_score
df['improvement_pct'] = np.round((df['improvement'] / df['pre_score']) * 100, 2)

# 2. Advanced: Apply a custom function to every single row
# Example: Categorize attention scores
# Logic: If attention >= 90 is "High", otherwise "Standard"
df['attention_rating'] = df['attention_score'].apply(lambda x: 'High' if x >= 90 else 'Standard')

print(df[['Name', 'improvement_pct', 'attention_score','attention_rating']])

<font size="4">**3. Removing Columns**</font>

<font size="4">Use `.drop()` method. You must specify axis=1 (columns) because the default is axis=0 (rows).</font>

In [ ]:
# Option A: Return a new copy (Safe)
# Create a new DataFrame 'df_anonymous' by removing personal identifiers
df_anonymous = df.drop(['Name', 'Surname'], axis=1)

# Check the new DF (Original 'df' is untouched)
print("Anonymous DataFrame (No Names):")
print(df_anonymous.head(10))

print("*"*100)
print("*"*100)
print("*"*100)
# Option B: Modify the original DataFrame directly (Efficient)
# Permanently remove the 'attention_score' column from 'df'
df_anonymous.drop(['attention_score'], axis=1, inplace=True)
print("\nOriginal DataFrame (attention_score removed):")
print(df_anonymous.head(3))

In [ ]:
# Dropping single participants
# Using .drop() with Index
# This is useful if you set 'Name' as your index first.
df_indexed = df.set_index('Name')

# Now you can drop directly by name because they are the row labels
df_dropped = df_indexed.drop(['Charlie', 'David'], axis=0) 

# Restore the index (bring 'Name' back as a column)
# 'drop=False' is default: it keeps the old index as a column.
df_final = df_dropped.reset_index()

print("\nDataFrame after dropping Charlie and David:")
print(df_final)

In [ ]:
# ---------------------------------------------------------
# EXERCISE 4: Data Manipulation
# ---------------------------------------------------------

# 0. Setup: Recreating the DataFrame from Exercise 3
#    (We need this data to exist before we can manipulate it!)

#np.random.seed(42)
#df = pd.DataFrame({
#    'id': range(1, 13),
#    'age': np.random.randint(18, 36, 12),
#    'group': np.random.choice(['A', 'B', 'C'], 12),
#    'anxiety_score': np.random.randint(1, 11, 12),
#    'depression_score': np.random.randint(1, 11, 12)
#})

#print(df.head(), "\n")

# 1. Create a 'combined_score' column (Sum of anxiety and depression).
#    Psychological Context: Creating a total scale score from two sub-scales.
#    Hint: You can add columns directly like: df['new_col'] = df['col_A'] + df['col_B']

# ... write your code here ...


# 2. Create a binary 'high_risk' column.
#    Logic: True if combined_score is strictly greater than 14.
#    Psychological Context: Applying a clinical cut-off point for screening.
#    Hint: This is a boolean operation (>, <, ==) which returns True/False.

# ... write your code here ...


# 3. Standardization: Create 'anxiety_z' (Z-score).
#    Psychological Context: Standardizing scores (z = (x - mean) / std) allows comparison across different tests.
#    Hint: Calculate mean and std of 'anxiety_score' first, then apply the formula.

# ... write your code here ...


# 4. Recoding: Create 'age_group' column.
#    Logic: 'Young' if age < 25, else 'Adult'.
#    Hint: Use df['age'].apply(lambda x: ...) OR np.where(condition, 'Val_if_True', 'Val_if_False').

# ... write your code here ...


# 5. Remove the original 'depression_score' column.
#    Hint: Use .drop(). Remember to specify the axis (1 for columns) and inplace=True.

# ... write your code here ...


# 6. View the Final Transformed DataFrame
#    Hint: Just print(df) or print(df.head()) to verify your changes.

# ... write your code here ...


<details> <summary>Click here to see the solution 💡</summary> 
    <br>
    <b> Solution:</b> 
    <pre>
        
<font size="2">**0. Setup (Required to run the code)**</font> 
        np.random.seed(42) 
        df = pd.DataFrame({ 
        'id': range(1, 13), 
        'age': np.random.randint(18, 36, 12), 
        'group': np.random.choice(['A', 'B', 'C'], 12), 
        'anxiety_score': np.random.randint(1, 11, 12), 
        'depression_score': np.random.randint(1, 11, 12) 
    })
        
<font size="2">**1. Combined Score (Vectorized Sum)**</font>

df['combined_score'] = df['anxiety_score'] + df['depression_score']

<font size="2">**2. High Risk (Binary Logic)**</font>
<font size="2">Creates True/False based on the threshold</font>
df['high_risk'] = df['combined_score'] > 14

<font size="2">**3. Standardization (Z-Score)**</font>
<font size="2">Step-by-step calculation</font>

anxiety_mean = df['anxiety_score'].mean()
anxiety_std = df['anxiety_score'].std()

df['anxiety_z'] = (df['anxiety_score'] - anxiety_mean) / anxiety_std

<font size="2">**4. Recoding (Lambda Function)**</font>
<font size="2">Apply logic row-by-row to categorize age</font>

df['age_group'] = df['age'].apply(lambda x: 'Young' if x < 25 else 'Adult')

<font size="2">**5. Drop Column**</font>
<font size="2">Removing the raw 'depression_score'</font>

df.drop(['depression_score'], axis=1, inplace=True)

<font size="2">**6. Check Results**</font>
print(df.head())
</pre>

<b>
    Expected Output (with seed=42):
</b>

<pre> 
     id  age group  anxiety_score  combined_score  high_risk  anxiety_z  \
0   1   24     B             10              12      False   1.585650   
1   2   32     B              3               7      False  -1.189237   
2   3   28     B              7              16       True   0.396412   
3   4   25     A              4               6      False  -0.792825   
4   5   24     A              9              19       True   1.189237   

  age_group  
0     Young  
1     Adult  
2     Adult  
3     Adult  
4     Young  
</pre>
<p><i><b>Important:</b> Notice that <code>depression_score</code> is gone from the final output. Also, the <code>anxiety_z</code> column shows how many standard deviations a score is from the mean (e.g., ID 3 is 1.4 std devs above average).</i></p>
</details>

<font size="4">**Handling Missing Data**</font>

<font size="4">In real psychological research, participants often skip questions or drop out of studies, leading to missing values. Pandas represents these as NaN (Not a Number) or None.</font>

<font size="4">**1. Detecting Missing Data**</font>

<font size="4">Before cleaning, you must assess the entity of missngness</font>

<font size="4">For this part, we need to create a dataframe with missing data. We start with the previous df created.</font>

In [ ]:
np.random.seed(42)

# Create the initial data dictionary
data_missing = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'Surname': ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis', 'Rodriguez', 'Martinez'],
    'pre_score': [56, 69, 78, np.nan, 60, 57, 78, np.nan, 56, 75],
    'post_score': [88, np.nan, 80, 80, 93, 90, 73, np.nan, 93, 72],    
    'attention_score': np.random.randint(60, 100, 10) # Attention check scores
}

# Create DataFrame
df_missing = pd.DataFrame(data_missing)

# 1. From Calculation (Vectorized Math)
# Calculates row-by-row automatically
df_missing['improvement'] = df_missing['post_score'] - df_missing['pre_score']

# 2. From Boolean Logic (True/False)
df_missing['passed_check'] = df_missing['attention_score'] >= 80

# 3. Constant Value (Assigns same string/number to EVERY row)
df_missing['study_version'] = 'Pilot_v1'

df_missing['improvement_pct'] = np.round((df_missing['improvement'] / df_missing['pre_score']) * 100, 2)

df_missing['attention_rating'] = df_missing['attention_score'].apply(lambda x: 'High' if x >= 90 else 'Standard')


df_missing.head(10)

In [ ]:
# Check for missing values (Returns True if missing)
print(df_missing.isnull().head()) 

print("*"*100)

# The most useful command: Count missing values per column
print(df_missing.isnull().sum())

<font size="4">When dealing with NaN values, it's crucial to ask why the data is missing. In statistics and psychology, missing data is categorized into three types. Understanding these helps you decide whether to delete rows, fill them (impute), or flag them as a bias.

- <font size="4">**1. MCAR: Missing Completely at Random**</font>

<font size="4">There is no pattern to the missingness. It is purely accidental. The probability of missing data is unrelated to any other variable in your study.

<font size="4">Example: A participant accidentally skips a question because they turned two pages at once.

<font size="4">Solution: Safe to remove rows (listwise deletion) without introducing bias.

- <font size="4">**2. MAR: Missing at Random**</font>
<font size="4">The missingness is systematic but can be explained by other observed variables in your dataset. It is not related to the missing value itself, but to something else you measured.</font>

<font size="4">Example: Men are more likely to skip a "Depression Score" question than women. If you have a column for Gender, you can see this pattern.</font>

<font size="4">Solution: Do not just delete rows (this biases your sample towards women). Instead, use imputation (filling values) based on the group (e.g., fill missing male scores with the male median).</font>

- <font size="4">**3. MNAR: Missing Not at Random**</font>
<font size="4">The most dangerous type. The missingness is related to the value itself (which is missing!).</font>

<font size="4">Example: Participants with very high anxiety are too anxious to complete the anxiety questionnaire.</font>

<font size="4">Consequence: Your dataset will underestimate the true anxiety levels of your population because the highest scores are systematically missing.</font>

<font size="4">Solution: Very difficult to fix. Simple imputation or deletion will bias your results. You often need advanced statistical modeling or to explicitly acknowledge this limitation.</font>

<font size="4">**Strategy A: Removing Data (Listwise Deletion)**</font>

<font size="4">In an MCAR scenario


In [ ]:
# Drop rows with ANY missing values (Be careful, you might lose too much data!)
df_clean_MCAR = df_missing.dropna()

print(df_clean_MCAR)

print("*"*100)

# Drop rows ONLY if they are missing critical data (e.g., 'age')
df_clean_specific_MCAR = df_missing.dropna(subset=['pre_score'])

print(df_clean_specific_MCAR)

<font size="4">**Strategy B: Imputation (Filling Data)**</font>

<font size="4">In an MAR scenario

In [ ]:
df_missing_MAR_1 = df_missing.copy()
df_missing_MAR_2 = df_missing.copy()
df_missing_MAR_3 = df_missing.copy()

In [ ]:
# Option 1: Fill with a constant (e.g., 0 for a score)
df_missing_MAR_1['pre_score'] = df_missing_MAR_1['pre_score'].fillna(0)
print(df_missing_MAR_1)

print("*"*100)

# Option 2: Mean Imputation (Common for continuous variables like pre_score)
mean_pre_score = df_missing_MAR_2['pre_score'].mean()
df_missing_MAR_2['pre_score'] = df_missing_MAR_2['pre_score'].fillna(mean_pre_score)
print(df_missing_MAR_2)

print("*"*100)

# Option 3: Fill different columns differently
df_missing_MAR_3.fillna({
    'pre_score': df_missing_MAR_3['pre_score'].median(), 
    'post_score': 90,                 
    'improvement_pct': 'Unknown'          
}, inplace=True)
print(df_missing_MAR_3)
print("*"*100)

In [ ]:
# ---------------------------------------------------------
# EXERCISE 5: Handling Missing Values
# ---------------------------------------------------------

# 0. Setup: Create a DataFrame with intentionally missing data (NaN)
np.random.seed(99)
df_missing = pd.DataFrame({
    'subject_id': range(101, 111),
    'age': [25, np.nan, 30, 22, np.nan, 28, 35, 29, np.nan, 24],
    'reaction_time': [250, 300, np.nan, 240, 310, np.nan, 290, 260, 280, np.nan],
    'group': ['Control', 'Exp', 'Control', 'Exp', 'Exp', 'Control', 'Exp', 'Control', 'Exp', 'Control']
})

print("--- Original DataFrame with Missing Data ---")
print(df_missing)
print("\n")


# 1. Identification:
#    Print the count of missing values for each column to see which variables are incomplete.
#    Hint: Use .isnull().sum()

# ... write your code here ...


# 2. Strategy A: Imputation (Filling)
#    Create a copy of the dataframe (so we don't affect the original for Strategy B).
#    Fill the missing 'age' values with the median age of the group.
#    Hint: Use df_imputed = df_missing.copy() first.
#    Hint: Calculate median, then use .fillna().

# ... write your code here ...


# 3. Strategy B: Deletion (Dropping)
#    Create another copy of the original dataframe.
#    Drop any row that has at least one missing value.
#    Hint: Use .dropna()

# ... write your code here ...


# 4. Comparison:
#    Print the shape (number of rows/cols) of both new DataFrames.
#    How many participants did you "save" by imputing instead of dropping?

# ... write your code here ...


<details> 
<summary>Click here to see the solution 💡</summary> 
    <br>
    <b> Solution:</b> 
    <pre> 

<font size="2">**1. Identification**</font> 
print("Missing Values Count:") 
print(df_missing.isnull().sum())

<font size="2">**2. Strategy A: Imputation**</font>
df_imputed = df_missing.copy()
median_age = df_imputed['age'].median()
df_imputed['age'] = df_imputed['age'].fillna(median_age)
print("\nImputed DataFrame (Age filled):")
print(df_imputed.head())

<font size="2">**3. Strategy B: Deletion**</font>
df_dropped = df_missing.copy().dropna()
print("\nDropped DataFrame (Rows removed):")
print(df_dropped.head())

<font size="2">**4. Comparison**</font>
print(f"\nOriginal Size: {df_missing.shape} rows")
print(f"Imputed Size: {df_imputed.shape} rows (Kept all participants)")
print(f"Dropped Size: {df_dropped.shape} rows (Lost participants)")
</pre>

<b>Expected Output:</b>

<pre> 
Missing Values Count:
subject_id       0
age              3
reaction_time    3
group            0

Imputed DataFrame (Age filled):
   subject_id   age  reaction_time    group
0         101  25.0          250.0  Control
1         102  28.0          300.0      Exp
2         103  30.0            NaN  Control
3         104  22.0          240.0      Exp
4         105  28.0          310.0      Exp

Dropped DataFrame (Rows removed):
   subject_id   age  reaction_time    group
0         101  25.0          250.0  Control
3         104  22.0          240.0      Exp
6         107  35.0          290.0      Exp
7         108  29.0          260.0  Control

Original Size: (10, 4) rows
Imputed Size: (10, 4) rows (Kept all participants)
Dropped Size: (4, 4) rows (Lost participants)
</pre> 

<p><i><b>Insight:</b> Notice that simply dropping rows with ANY missing data reduced our sample size by 60% (from 10 to 4). Imputation allowed us to keep those participants for analysis, though we must be careful about the assumptions we make when filling data.</i></p> </details>

<font size="4">**Grouping and Aggregating Data**</font>
<font size="4">One of the most powerful features in Pandas is `.groupby()`. It follows the "Split-Apply-Combine" logic:</font>

- <font size="4">Split: Break the data into smaller buckets based on a category (e.g., Therapy Group).</font>

- <font size="4">Apply: Perform a calculation on each bucket separately (e.g., calculate the mean).</font>

- <font size="4">Combine: Put the results back together into a new table.</font>

In [ ]:
data = {
    'participant_id': range(1, 13),
    'condition': ['A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B', 'B'],
    'gender':    ['Male', 'Male', 'Male', 'Female', 'Female', 'Female', 
                  'Male', 'Male', 'Male', 'Female', 'Female', 'Female'],
    'score':     [10, 12, 11,   20, 22, 21,   # Cond A: Women score higher (~21 vs ~11)
                   30, 32, 31,   15, 14, 16]    # Cond B: Men score higher (~31 vs ~15)
}

df_multi = pd.DataFrame(data)

print("--- Original DataFrame ---")
print(df_multi)
print("\n")

<font size="4">**Basic Grouping**</font>

In [ ]:
# "For each condition, what is the average score?"
# 1. Split by 'condition' -> 2. Select 'score' column -> 3. Calculate Mean
mean_scores = df_multi.groupby('condition')['score'].mean()
print(mean_scores)

<font size="4">**Advanced Aggregation (`.agg`)**</font>

<font size="4">You often need more than just the mean (e.g., standard deviation to see variability, or count to check sample size).</font>

In [ ]:
# Get Mean, Std Dev, and Count all at once
group_stats = df_multi.groupby('condition')['score'].agg(['mean', 'std', 'count'])
print(group_stats)

<font size="4">**Grouping by Multiple Variables**</font>

<font size="4">You can slice your data by multiple factors simultaneously (e.g., Gender AND Condition).</font>

In [ ]:
# "What is the average score for Men in A vs. Women in A?"
interaction = df_multi.groupby(['condition', 'gender'])['score'].mean()
print(interaction)

In [ ]:
# ---------------------------------------------------------
# EXERCISE 7: Group Analysis (The "Split-Apply-Combine" Method)
# ---------------------------------------------------------

# 0. Setup: Create the Clinical Trial Data
np.random.seed(123)
df_therapy = pd.DataFrame({
    'participant_id': range(1, 21),
    'therapy': np.random.choice(['CBT', 'Psychodynamic', 'Control'], 20),
    'pre_score': np.random.randint(10, 30, 20),   # Depression scale (0-40)
    'post_score': np.random.randint(5, 25, 20)
})
print(df_therapy)

# 1. Calculate the 'improvement' column (pre - post).
#    (Positive number means symptoms went down/improved)

# ... write your code here ...


# 2. Basic Grouping:
#    Group by 'therapy' and calculate the mean of 'pre_score' and 'post_score'.
#    Hint: df.groupby('...')[['col1', 'col2']].mean()

# ... write your code here ...


# 3. Aggregation:
#    Group by 'therapy' again, but this time analyze the 'improvement' column.
#    Use .agg() to get the 'mean', 'std' (standard deviation), and 'count'.
#    This tells us which therapy worked best, how consistent it was, and the N per group.

# ... write your code here ...


# 4. Critical Thinking:
#    Print the results. Which group had the highest mean improvement?
#    Did the Control group improve?

# ... write your code here ...


<details> 
<summary>Click here to see the solution 💡</summary> 
    <br> 
    <b> Solution:</b> 
    <pre> 

<font size="2">**1. Calculate Improvement**</font> 
df_therapy['improvement'] = df_therapy['pre_score'] - df_therapy['post_score']

<font size="2">**2. Mean Scores by Group**</font>
<font size="2">Select multiple columns by using a list [['col1', 'col2']]</font>
means = df_therapy.groupby('therapy')[['pre_score', 'post_score']].mean()
print("--- Mean Scores Before & After ---")
print(means)

<font size="2">**3. Detailed Stats on Improvement**</font>
stats = df_therapy.groupby('therapy')['improvement'].agg(['mean', 'std', 'count'])
print("\n--- Therapy Effectiveness (Improvement) ---")
print(stats)

<font size="2">**4. Formatting (Optional)**</font>
<font size="2">Round to 2 decimal places for cleaner output</font>
print("\n--- Cleaned Output ---")
print(stats.round(2))
</pre>

<b>Expected Output (with seed=123):</b>

<pre> 
Name: improvement, dtype: int32
--- Mean Scores Before & After ---
               pre_score  post_score
therapy                             
CBT            20.000000   17.250000
Control        16.444444   15.555556
Psychodynamic  17.142857   12.142857

--- Therapy Effectiveness (Improvement) ---
                   mean        std  count
therapy                                  
CBT            2.750000  10.750969      4
Control        0.888889   9.373426      9
Psychodynamic  5.000000   6.377042      7

--- Cleaned Output ---
               mean    std  count
therapy                          
CBT            2.75  10.75      4
Control        0.89   9.37      9
Psychodynamic  5.00   6.38      7
</pre> 

<p><i><b>Interpretation:</b> In this random simulation, <b>Psychodynamic</b> appears most effective (Mean improvement = +5.00). The <b>Control</b> group actually got worse (Mean = 0.89), suggesting the condition might worsen without treatment. The <b>CBT</b> group showed slight improvement (+2.75), but had high variability (std = 10.75).</i></p> </details>